version: '3.9'

services:
  mysql:
    image: 'mysql:8.0.32'
    container_name: mysql
    command:
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --lower_case_table_names=1
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_PASS: root
      TZ: Asia/Shanghai
    volumes:
      - d:/db/mysql/data:/var/lib/mysql
    ports:
      - '3306:3306'
  redis:
    image: 'redis:7.0.10-alpine'
    container_name: redis
    restart: always
    volumes:
      - d:/db/redis/data:/data
    ports:
      - '6379:6379'
  activemq:
    image: 'fushixin/activemq:5.16.6'
    container_name: activemq
    restart: always
    volumes:
      - d:/db/activemq/data:/usr/local/docker/activemq/data
    ports:
      - '1099:1099'
      - '1883:1883'
      - '8161:8161'
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    container_name: zookeeper
    restart: always
    volumes:
      - d:/db/zookeeper/data:/bitnami/zookeeper/data
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - '2181:2181'
  kafka:
    image: 'bitnami/kafka:latest'
    container_name: kafka
    restart: always
    volumes:
      - d:/db/kafka/data:/bitnami/kafka/data
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    ports:
      - '9092:9092'
    depends_on:
      - zookeeper