version: "3.0"

services:
  # 最后一个免费版本
  minio:
    image: minio/minio:RELEASE.2021-04-22T15-44-28Z
    container_name: minio-server
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin123
    volumes:
      - E:\data:/data
    command: server /data
    ports:
      - "9000:9000"
    restart: always
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3